<a href="https://colab.research.google.com/github/bum3632/pdm13/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [2]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]] #2차원 리스트
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [3]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# data.shape # Error!
# convert to a numpy array
data = asarray(data) # 리스트 형태였던 data의 형태가 바뀜
# step through rows
for row in range(data.shape[0]):
	print(data[row])

[1 2 3]
[4 5 6]


In [5]:
data.shape,data.shape[0],data.shape[1] #첫번째 data.shape은 튜플, 두번째는 인덱스 0이므로 2, 세번째는 인덱스 1이므로 3이 출력된다.

((2, 3), 2, 3)

## Print columns

In [7]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col]) # col은 열을 뜻하기 때문에 첫번째 열부터 출력되라는 것이다.

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [11]:
# sum values array-wise
from numpy import asarray  #column-wise는 열을, row-wise는 행을 뜻한다.
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum() #배열에 sum 함수가 걸리면 총합을 뜻한다. 뒤의 axis의 값에 따라 다른 결과물이 출력된다. ex) axis값이 0이면 열의 합(세로), 1이면 가로 합이다.
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


### Axis=0 Column-Wise Operation (수직으로)

In [12]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0) #뒤의 axis의 값에 따라 다른 결과물이 출력된다. ex) axis값이 0이면 열의 합(세로), 1이면 가로 합이다.
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [13]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1) #뒤의 axis의 값에 따라 다른 결과물이 출력된다. ex) axis값이 0이면 열의 합(세로), 1이면 가로 합이다.
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''